# Experiment 1: Code Injection

## Clean Dataset
We know we can inject our function into the coreutils binaries. How about the others?

- [x] Coreutils (~~105~~ 109 binaries)
- [ ] ~~Debianutils (8 binaries)~~
- [x] Util-linux (~~81~~ 74 binaries)
- [x] Diffutils (~~4~~ 5 binaries)
- [ ] ~~Findutils (~~2~~ 4 binaries)~~
- [x] Inetutils (28 binaries)


In [20]:
find_bins_outputs = {}

# Coreutils (for posterity)
find_bins_outputs['coreutils'] = !find_bins ../../dataset-gen/coreutils-8.31/ | grep -v gnulib-tests | grep -v libstdbuf.so
# Returns 109 binaries
find_bins_outputs['coreutils'] 

['../../dataset-gen/coreutils-8.31/src/[',
 '../../dataset-gen/coreutils-8.31/src/b2sum',
 '../../dataset-gen/coreutils-8.31/src/base32',
 '../../dataset-gen/coreutils-8.31/src/base64',
 '../../dataset-gen/coreutils-8.31/src/basename',
 '../../dataset-gen/coreutils-8.31/src/basenc',
 '../../dataset-gen/coreutils-8.31/src/cat',
 '../../dataset-gen/coreutils-8.31/src/chcon',
 '../../dataset-gen/coreutils-8.31/src/chgrp',
 '../../dataset-gen/coreutils-8.31/src/chmod',
 '../../dataset-gen/coreutils-8.31/src/chown',
 '../../dataset-gen/coreutils-8.31/src/chroot',
 '../../dataset-gen/coreutils-8.31/src/cksum',
 '../../dataset-gen/coreutils-8.31/src/comm',
 '../../dataset-gen/coreutils-8.31/src/cp',
 '../../dataset-gen/coreutils-8.31/src/csplit',
 '../../dataset-gen/coreutils-8.31/src/cut',
 '../../dataset-gen/coreutils-8.31/src/date',
 '../../dataset-gen/coreutils-8.31/src/dd',
 '../../dataset-gen/coreutils-8.31/src/df',
 '../../dataset-gen/coreutils-8.31/src/dir',
 '../../dataset-gen/coreut

### [debianutils](https://salsa.debian.org/debian/debianutils)
First off, there's probably less than 8 binaries in this one, as some appear to be shell scripts. Second, there's no obvious way to compile these applications and no documentation. Skipping this for now...

### [util-linux](https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.35/)
Ran `./configure` without issue, then modified Makefile and changed value of `STRIP` var to `true`. Ran `make -j5` and found all binaries plopped at root of source tree.

74 binaries discovered here. Found this little handy command for finding all actual ELF binaries in package (last line is count):
```bash
tree -nif --noreport|grep -v '>'|xargs file|grep "ELF.*shared object"|cut -d':' -f1|tee /dev/tty|wc -l
```

In [21]:
find_bins_outputs['util-linux'] = !find_bins ../../dataset-gen/util-linux-2.35/ 
find_bins_outputs['util-linux']

['../../dataset-gen/util-linux-2.35/addpart',
 '../../dataset-gen/util-linux-2.35/agetty',
 '../../dataset-gen/util-linux-2.35/blkdiscard',
 '../../dataset-gen/util-linux-2.35/blkzone',
 '../../dataset-gen/util-linux-2.35/blockdev',
 '../../dataset-gen/util-linux-2.35/cal',
 '../../dataset-gen/util-linux-2.35/chcpu',
 '../../dataset-gen/util-linux-2.35/chfn',
 '../../dataset-gen/util-linux-2.35/chmem',
 '../../dataset-gen/util-linux-2.35/choom',
 '../../dataset-gen/util-linux-2.35/chrt',
 '../../dataset-gen/util-linux-2.35/chsh',
 '../../dataset-gen/util-linux-2.35/col',
 '../../dataset-gen/util-linux-2.35/colcrt',
 '../../dataset-gen/util-linux-2.35/colrm',
 '../../dataset-gen/util-linux-2.35/ctrlaltdel',
 '../../dataset-gen/util-linux-2.35/delpart',
 '../../dataset-gen/util-linux-2.35/dmesg',
 '../../dataset-gen/util-linux-2.35/fallocate',
 '../../dataset-gen/util-linux-2.35/fdformat',
 '../../dataset-gen/util-linux-2.35/flock',
 '../../dataset-gen/util-linux-2.35/fsck.cramfs',
 '../

### [diffutils](https://ftp.gnu.org/gnu/diffutils/)
Ran `./configure` and `make -j5` without issue. Found 5 binaries here, one is a tester.

In [22]:
find_bins_outputs['diffutils'] = !find_bins ../../dataset-gen/diffutils-3.7/
find_bins_outputs['diffutils']

['../../dataset-gen/diffutils-3.7/gnulib-tests/test-localcharset',
 '../../dataset-gen/diffutils-3.7/src/cmp',
 '../../dataset-gen/diffutils-3.7/src/diff',
 '../../dataset-gen/diffutils-3.7/src/diff3',
 '../../dataset-gen/diffutils-3.7/src/sdiff']

### ~~[findutils](https://ftp.gnu.org/pub/gnu/findutils/)~~
~~Ran `./configure` and `make -j5` without issue. Found 5 binaries here, one is a tester (**same tester as above! don't duplicate!**).~~
*Disabled findutils so we could have a nice even 215 applications*

```
find_bins_outputs['findutils'] = !find_bins ../../dataset-gen/findutils-4.7.0/ | grep -v gnulib-tests
find_bins_outputs['findutils']
```

### [inetutils](https://ftp.gnu.org/gnu/inetutils/)
Ran `./configure` and `make -j5` without issue. Found 28 binaries here

In [23]:
find_bins_outputs['inetutils'] = !find_bins ../../dataset-gen/inetutils-1.9.4/
find_bins_outputs['inetutils']

['../../dataset-gen/inetutils-1.9.4/ftp/ftp',
 '../../dataset-gen/inetutils-1.9.4/ftpd/ftpd',
 '../../dataset-gen/inetutils-1.9.4/ifconfig/ifconfig',
 '../../dataset-gen/inetutils-1.9.4/ping/ping',
 '../../dataset-gen/inetutils-1.9.4/ping/ping6',
 '../../dataset-gen/inetutils-1.9.4/src/dnsdomainname',
 '../../dataset-gen/inetutils-1.9.4/src/hostname',
 '../../dataset-gen/inetutils-1.9.4/src/inetd',
 '../../dataset-gen/inetutils-1.9.4/src/logger',
 '../../dataset-gen/inetutils-1.9.4/src/rcp',
 '../../dataset-gen/inetutils-1.9.4/src/rexec',
 '../../dataset-gen/inetutils-1.9.4/src/rexecd',
 '../../dataset-gen/inetutils-1.9.4/src/rlogin',
 '../../dataset-gen/inetutils-1.9.4/src/rlogind',
 '../../dataset-gen/inetutils-1.9.4/src/rsh',
 '../../dataset-gen/inetutils-1.9.4/src/rshd',
 '../../dataset-gen/inetutils-1.9.4/src/syslogd',
 '../../dataset-gen/inetutils-1.9.4/src/tftp',
 '../../dataset-gen/inetutils-1.9.4/src/tftpd',
 '../../dataset-gen/inetutils-1.9.4/src/traceroute',
 '../../dataset-

In [24]:
#flat_list = [item for sublist in l for item in sublist]
clean_bin_paths = list([str(x) for sublist in find_bins_outputs.values() for x in sublist])
len(clean_bin_paths)

215

## Fingerprint Clean Dataset

In [25]:
import ace
import pandas as pd
import time
import os

def get_src_dir(bin_path, dataset_path):
    dn = os.path.dirname(bin_path)
    if os.path.abspath(dn) == os.path.abspath(dataset_path):
        return os.path.abspath(bin_path)
    elif dn == "/":
        return None
    else:
        return get_src_dir(dn, dataset_path)
        

clean_profiles=[]
clean_runtimes={}
for bin_path in clean_bin_paths:
    if os.path.isfile(bin_path):
        src_path = get_src_dir(bin_path, "../../dataset-gen")
        start = time.monotonic()
        print("Profiling {} ({} KB)".format(bin_path, os.path.getsize(bin_path)/1000))
        clean_profiles.append(ace.full_profile(bin_path, 
                                               threads = 8, 
                                               ins_sort = True, 
                                               src_only = True, 
                                               src_path = src_path
                                              )
                             )
        clean_runtimes[bin_path] = time.monotonic() - start

Profiling ../../dataset-gen/coreutils-8.31/src/[ (226.52 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/b2sum (289.424 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/base32 (182.936 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/base64 (182.32 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/basename (145.352 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/basenc (225.824 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/cat (167.848 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/chcon (297.872 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/chgrp (292.136 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/chmod (277.672 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/chown (304.232 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/chroot (180.664 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/cksum (154.72 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/comm (178.856 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/cp (710.408 KB)
Profiling ../../

Profiling ../../dataset-gen/coreutils-8.31/src/tr (209.904 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/true (133.272 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/truncate (165.68 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/tsort (173.528 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/tty (139.136 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/uname (142.496 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/unexpand (165.152 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/uniq (206.152 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/unlink (142.68 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/uptime (215.16 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/users (152.512 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/vdir (628.536 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/wc (218.4 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/who (227.96 KB)
Profiling ../../dataset-gen/coreutils-8.31/src/whoami (143.064 KB)
Profiling ../../data

In [26]:
clean_fps = pd.concat(clean_profiles, ignore_index=True)
clean_fps

binary               function  \
0             ../../dataset-gen/coreutils-8.31/src/[                 beyond   
1             ../../dataset-gen/coreutils-8.31/src/[        binary_operator   
2             ../../dataset-gen/coreutils-8.31/src/[                  binop   
3             ../../dataset-gen/coreutils-8.31/src/[  clone_quoting_options   
4             ../../dataset-gen/coreutils-8.31/src/[           close_stdout   
...                                              ...                    ...   
16785  ../../dataset-gen/inetutils-1.9.4/whois/whois               xnmalloc   
16786  ../../dataset-gen/inetutils-1.9.4/whois/whois              xnrealloc   
16787  ../../dataset-gen/inetutils-1.9.4/whois/whois               xrealloc   
16788  ../../dataset-gen/inetutils-1.9.4/whois/whois                xstrdup   
16789  ../../dataset-gen/inetutils-1.9.4/whois/whois                xzalloc   

       address  length                                           src_path  \
0         7168      60  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...   
1         7280    1389  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...   
2         6400     362  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...   
3        18720      54  /home/ubuntu/ace/dataset-gen/coreutils-8.31/li...   
4        12960     164  /home/ubuntu/ace/dataset-gen/coreutils-8.31/li...   
...        ...     ...                                                ...   
16785    37648      22  /home/ubuntu/ace/dataset-gen/inetutils-1.9.4/l...   
16786    37760      22  /home/ubuntu/ace/dataset-gen/inetutils-1.9.4/l...   
16787    37696      54  /home/ubuntu/ace/dataset-gen/inetutils-1.9.4/l...   
16788    38112      19  /home/ubuntu/ace/dataset-gen/inetutils-1.9.4/l...   
16789    38000      23  /home/ubuntu/ace/dataset-gen/inetutils-1.9.4/l...   

       src_line                                           src_code attributor  \
0         124.0  beyond (void)\n{\n  test_syntax_error (_("miss...       nm-t   
1         271.0  binary_operator (bool l_is_l)\n{\n  int op;\n ...       nm-t   
2         183.0  binop (char const *s)\n{\n  return ((STREQ (s,...       nm-t   
3         122.0  clone_quoting_options (struct quoting_options ...       nm-T   
4         117.0  close_stdout (void)\n{\n  if (close_stream (st...       nm-T   
...         ...                                                ...        ...   
16785     104.0  xnmalloc (size_t n, size_t s)\n{\n  if (xalloc...       nm-T   
16786     117.0  xnrealloc (void *p, size_t n, size_t s)\n{\n  ...       nm-T   
16787      51.0  xrealloc (void *p, size_t n)\n{\n  if (!n && p...       nm-T   
16788     119.0  xstrdup (char const *string)\n{\n  return xmem...       nm-T   
16789      84.0  xzalloc (size_t s)\n{\n  return memset (xmallo...       nm-T   

                                               raw_bytes  \
0      b'Hc\x15\xb1\xa4 \x00H\x8b\x05\xa2\xa4 \x00SH\...   
1      b'AWAV\x89\xf8AUATUSH\x81\xecx\x01\x00\x00\x8b...   
2      b'I\x89\xf8H\x8d=\xfbi\x00\x00\xb9\x02\x00\x00...   
3      b'ATUSH\x89\xfb\xe8$\xca\xff\xffD\x8b H\x89\xc...   
4      b'USH\x83\xec\x08H\x8b=\xdb\x8d \x00\xe8^-\x00...   
...                                                  ...   
16785  b'H\x89\xf8H\xf7\xe6p\x05H\x89\xc7\xeb\xd3H\x8...   
16786  b'H\x89\xf0H\xf7\xe2p\x05H\x89\xc6\xeb\xb3H\x8...   
16787  b'H\x85\xf6SH\x89\xf3u\x05H\x85\xffu\x1aH\x89\...   
16788  b'SH\x89\xfb\xe8G\xc7\xff\xffH\x89\xdfH\x8dp\x...   
16789  b'SH\x89\xfb\xe8w\xfe\xff\xffH\x89\xda1\xf6H\x...   

                                             fingerprint  
0      [2139297, -2147483647, 130, -131072, 2139297, ...  
1      [376, 0, 2147483647, 8388607, 0, 2147483647, -...  
2      [1, -2147483647, 128, 0, -1, -1, 19252, -1, 0,...  
3      [0, -2147483647, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,...  
4      [8, -2147483647, -2145350182, 0, 0, -214535018...  
...                                                  ...  
16785  [0, -2147483647, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0...  
16786 

## Injected Dataset

Excellent. Now that we have the fingerprints, let's identify the files in which to inject the code. I believe it's a safe assumption that the file containing `main()` is a good candidate

In [27]:
main_mask = clean_fps['function'] == "main"
clean_fps[main_mask]

binary function  address  \
14                ../../dataset-gen/coreutils-8.31/src/[     main     5680   
105           ../../dataset-gen/coreutils-8.31/src/b2sum     main     7088   
171          ../../dataset-gen/coreutils-8.31/src/base32     main     6144   
235          ../../dataset-gen/coreutils-8.31/src/base64     main     6144   
295        ../../dataset-gen/coreutils-8.31/src/basename     main     5392   
...                                                  ...      ...      ...   
16390    ../../dataset-gen/inetutils-1.9.4/telnet/telnet     main    21472   
16572  ../../dataset-gen/inetutils-1.9.4/telnetd/telnetd     main    13344   
16673   ../../dataset-gen/inetutils-1.9.4/tests/identify     main     1840   
16688         ../../dataset-gen/inetutils-1.9.4/tests/ls     main     4880   
16758      ../../dataset-gen/inetutils-1.9.4/whois/whois     main    24400   

       length                                           src_path  src_line  \
14        442  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     805.0   
105      5195  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     861.0   
171      2041  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...    1092.0   
235      2041  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...    1092.0   
295       479  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     124.0   
...       ...                                                ...       ...   
16390     585  /home/ubuntu/ace/dataset-gen/inetutils-1.9.4/t...     335.0   
16572     182  /home/ubuntu/ace/dataset-gen/inetutils-1.9.4/t...     212.0   
16673     480  /home/ubuntu/ace/dataset-gen/inetutils-1.9.4/t...      44.0   
16688       5  /home/ubuntu/ace/dataset-gen/inetutils-1.9.4/t...      24.0   
16758    1322  /home/ubuntu/ace/dataset-gen/inetutils-1.9.4/w...     203.0   

                                                src_code attributor  \
14     main (int margc, char **margv)\n{\n  bool valu...       nm-T   
105    main (int argc, char **argv)\n{\n  unsigned ch...       nm-T   
171    main (int argc, char **argv)\n{\n  int opt;\n ...       nm-T   
235    main (int argc, char **argv)\n{\n  int opt;\n ...       nm-T   
295    main (int argc, char **argv)\n{\n  bool multip...       nm-T   
...                                                  ...        ...   
16390  main (int argc, char *argv[])\n{\n  int index;...       nm-T   
16572  main (int argc, char **argv)\n{\n  int index;\...       nm-T   
16673  main (void)\n{\n  int a, ux;\n  struct utsname...       nm-T   
16688  main (int argc, char *argv[])\n{\n  return ls_...       nm-T   
16758  main (int argc, char *argv[])\n{\n  int index;...       nm-T   

                                               raw_bytes  \
14     b'US\x89\xfbH\x89\xf5H\x83\xec\x08H\x8b>\xe8]\...   
105    b'AWAVE1\xf6AUATA\x89\xfcUSH\x89\xf3L\x8d-\xd7...   
171    b'AWAVAUATA\x89\xfdUSI\x89\xf4\xbdL\x00\x00\x0...   
235    b'AWAVAUATA\x89\xfdUSI\x89\xf4\xbdL\x00\x00\x0...   
295    b'AVAUE1\xf6ATU\x89\xfdSH\x8b>H\x89\xf3E1\xedE...   
...                                                  ...   
16390  b'US\x89\xfbH\x89\xf5H\x83\xecxH\x8b>dH\x8b\x0...   
16572  b'US\x89\xfbH\x89\xf5H\x83\xec\x18H\x8b>dH\x8b...   
16673  b'SH\x81\xec\x90\x01\x00\x00H\x89\xe3H\x89\xdf...   
16688                                 b'\xe9[\n\x00\x00'   
16758  b'AWAVAUATA\x89\xfcUSH\x89\xf5H\x83\xec(H\x8b>...   

                                             fingerprint  
14     [8, -2147483647, 2147483647, 0, 0, 2147483647,...  
105    [328, -2147483647, -2147483648, -134217728, 0,...  
171    [120, -2147483647, -2147483648, -134217728, 0,...  
235    [120, -2147483647, -2147483648, -134217728, 0,...  
295    [0, -2147483647, 0, 0, 38505, 0, 0, 1, 1, 0, 0...  
...                                                  ...  
16390  [120, -2147483647, -2147483609, -134217726, 0,...  
16572  [24, -2147483647, -2147483609, -134217726, 0, ...  
16673  [400, -2147483647, -2147483609, -134217726, 0,...  
16688  [0, 0

In [28]:
# Confirm there's no duplicates (more than 1 main() per binary)
clean_fps[main_mask].duplicated(subset="binary").sum()

0

In [29]:
# Confirm there's no binaries without main()'s
set(clean_fps['binary'])-set(clean_fps[main_mask]['binary'])

set()

In [30]:
# Finally print the list of source files
injectable_files = list(clean_fps[main_mask]['src_path'])
injectable_files

['/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/test.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/md5sum.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/basenc.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/basenc.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/basename.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/basenc.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/cat.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/chcon.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/chgrp.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/chmod.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/chown.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/chroot.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/cksum.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/comm.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/cp.c',
 '/home/ubuntu/ace/dataset-gen/coreutils-8.31/src/csplit.c',
 '/home/ubuntu/ace/dataset-gen/coreuti

In [31]:
len(set(injectable_files)) 

202

Hmmm, so we have some cases where multiple applications put their main()'s in the same file... That should be okay, but let's look into it just in case

In [32]:
clean_fps[main_mask][clean_fps[main_mask].duplicated(subset="src_path", keep=False)]

binary function  address  \
14             ../../dataset-gen/coreutils-8.31/src/[     main     5680   
105        ../../dataset-gen/coreutils-8.31/src/b2sum     main     7088   
171       ../../dataset-gen/coreutils-8.31/src/base32     main     6144   
235       ../../dataset-gen/coreutils-8.31/src/base64     main     6144   
385       ../../dataset-gen/coreutils-8.31/src/basenc     main     6336   
2110         ../../dataset-gen/coreutils-8.31/src/dir     main    15120   
3090       ../../dataset-gen/coreutils-8.31/src/false     main     4992   
4325          ../../dataset-gen/coreutils-8.31/src/ls     main    15120   
4475      ../../dataset-gen/coreutils-8.31/src/md5sum     main     6400   
6986     ../../dataset-gen/coreutils-8.31/src/sha1sum     main     6400   
7053   ../../dataset-gen/coreutils-8.31/src/sha224sum     main     6400   
7124   ../../dataset-gen/coreutils-8.31/src/sha256sum     main     6400   
7195   ../../dataset-gen/coreutils-8.31/src/sha384sum     main     6400   
7266   ../../dataset-gen/coreutils-8.31/src/sha512sum     main     6400   
8582        ../../dataset-gen/coreutils-8.31/src/test     main     5648   
8880        ../../dataset-gen/coreutils-8.31/src/true     main     4992   
9569        ../../dataset-gen/coreutils-8.31/src/vdir     main    15120   
10550          ../../dataset-gen/util-linux-2.35/chfn     main    10032   
10860          ../../dataset-gen/util-linux-2.35/chsh     main     9328   

       length                                           src_path  src_line  \
14        442  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     805.0   
105      5195  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     861.0   
171      2041  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...    1092.0   
235      2041  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...    1092.0   
385      2857  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...    1092.0   
2110     6601  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...    1450.0   
3090      187  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...      55.0   
4325     6601  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...    1450.0   
4475     4413  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     861.0   
6986     4413  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     861.0   
7053     4413  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     861.0   
7124     4413  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     861.0   
7195     4413  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     861.0   
7266     4413  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     861.0   
8582      211  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...     805.0   
8880      178  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...      55.0   
9569     6601  /home/ubuntu/ace/dataset-gen/coreutils-8.31/sr...    1450.0   
10550    2978                                               None     403.0   
10860    1887                                               None     255.0   

                                                src_code attributor  \
14     main (int margc, char **margv)\n{\n  bool valu...       nm-T   
105    main (int argc, char **argv)\n{\n  unsigned ch...       nm-T   
171    main (int argc, char **argv)\n{\n  int opt;\n ...       nm-T   
235    main (int argc, char **argv)\n{\n  int opt;\n ...       nm-T   
385    main (int argc, char **argv)\n{\n  int opt;\n ...       nm-T   
2110   main (int argc, char **argv)\n{\n  int i;\n  s...       nm-T   
3090   main (int argc, char **argv)\n{\n  /* Recogniz...       nm-T   
4325   main (int argc, char **argv)\n{\n  int i;\n  s...       nm-T   
4475   main (int argc, char **argv)\n{\n  unsigned ch...       nm-T   
6986   main (int argc, char **argv)\n{\n  unsigned ch...       nm-T   
7053   main (int argc, char **argv)\n{\n  unsigned ch...       nm-T   
7124   main (int argc, char **argv)\n{\n  unsigned ch...       nm-T   
7195   main (int argc, char **argv)\n{\n  unsigned ch...      

Upon inspection, this seems okay, as most of the cases can be explained by those applications being very similar (e.g. `base32` and `base64`; `sha224sum` and `sha256sum`).

But looks like there's some `None`'s in the src_path field. Let's investigate

In [33]:
nosrc_mask = clean_fps['src_path'].isna()
clean_fps[main_mask & nosrc_mask]

binary function  address  length  \
10550  ../../dataset-gen/util-linux-2.35/chfn     main    10032    2978   
10860  ../../dataset-gen/util-linux-2.35/chsh     main     9328    1887   

      src_path  src_line src_code attributor  \
10550     None     403.0     None       nm-T   
10860     None     255.0     None       nm-T   

                                               raw_bytes  \
10550  b'AWAV\xb9\r\x00\x00\x00AUATA\x89\xfdUSI\x89\x...   
10860  b"AWAVE1\xf6AUATL\x8d-\xfe\x1f\x00\x00USH\x89\...   

                                             fingerprint  
10550  [152, -2147483647, 2147483643, 134217727, 0, 2...  
10860  [40, -2147483647, -2147483648, -134217728, 0, ...

Looks like two entries didn't get a src_path for some reason. I located them manually

In [34]:
clean_fps.at[10550, 'src_path'] = "/home/ubuntu/ace/dataset-gen/util-linux-2.35/login-utils/chfn.c"
clean_fps.at[10860, 'src_path'] = "/home/ubuntu/ace/dataset-gen/util-linux-2.35/login-utils/chsh.c"

Awesome, so now lets write that list to a file for archival purposes

In [35]:
injectable_files = list(clean_fps[main_mask]['src_path'])
with open('injectable_files.txt', 'w') as f:
    for item in injectable_files:
        f.write("%s\n" % item)

Actually, let's rewrite paths so that we don't modify our original clean copies

In [36]:
injectable_files_rw = [x.replace("/dataset-gen/", "/dataset-gen-injected/") for x in injectable_files]
with open('../../dataset-gen-injected/injectable_files_rw.txt', 'w') as f:
    for item in injectable_files_rw:
        f.write("%s\n" % item)

And we'll do the rewrite here

In [38]:
peaclab_math_src="""
int peaclab_math() {
    volatile int num;
    volatile int nabs;
    volatile div_t ndiv;
    volatile int result;
    volatile int array[16];
    unsigned short int i;
    
    for (i=0; i < 16; i++) {
        num = rand() / (RAND_MAX/360);
        array[i] = (i > 0) ? (array[i-1] + num) : num;
    }
    
    if (num > 100 ) {
        nabs = abs(num + 1);
    } else {
        nabs = abs(num - 1);
    }
    
    ndiv = div(nabs, 7);
    result = 2*(num * ndiv.quot) - nabs;

    return result;
}
"""
for src_path in injectable_files_rw:
    old_size = os.path.getsize(src_path)
    with open(src_path, 'a') as src_file:
        src_file.write(peaclab_math_src)
    new_size = os.path.getsize(src_path)
    print("Updated {}: {}B to {}B".format(os.path.basename(src_path), old_size, new_size))

Updated test.c: 22892B to 23394B
Updated md5sum.c: 31209B to 31711B
Updated basenc.c: 31392B to 31894B
Updated basenc.c: 31894B to 32396B
Updated basename.c: 5003B to 5505B
Updated basenc.c: 32396B to 32898B
Updated cat.c: 22071B to 22573B
Updated chcon.c: 16256B to 16758B
Updated chgrp.c: 8893B to 9395B
Updated chmod.c: 16055B to 16557B
Updated chown.c: 10143B to 10645B
Updated chroot.c: 11546B to 12048B
Updated cksum.c: 9819B to 10321B
Updated comm.c: 14239B to 14741B
Updated cp.c: 39811B to 40313B
Updated csplit.c: 39760B to 40262B
Updated cut.c: 16882B to 17384B
Updated date.c: 18181B to 18683B
Updated dd.c: 78126B to 78628B
Updated df.c: 55281B to 55783B
Updated ls.c: 161900B to 162402B
Updated dircolors.c: 12950B to 13452B
Updated dirname.c: 3199B to 3701B
Updated du.c: 34293B to 34795B
Updated echo.c: 7755B to 8257B
Updated env.c: 25851B to 26353B
Updated expand.c: 6184B to 6686B
Updated expr.c: 25516B to 26018B
Updated factor.c: 77243B to 77745B
Updated true.c: 2368B to 2870B
U

Oops, looks like some files got injected more than once.
 * /home/ubuntu/ace/dataset-gen-injected/coreutils-8.31/src/md5sum.c
 * /home/ubuntu/ace/dataset-gen-injected/coreutils-8.31/src/test.c
 * /home/ubuntu/ace/dataset-gen-injected/coreutils-8.31/src/basenc.c
 * /home/ubuntu/ace/dataset-gen-injected/coreutils-8.31/src/ls.c
 * /home/ubuntu/ace/dataset-gen-injected/coreutils-8.31/src/false.c
 
 Other files (specifically in util-linux and inetutils/tests) had to be modified to include `stdlib.h`. Some makes failed, but only because man pages were broken (all binaries still generated)
 
 Alright, let's find those bins again

In [37]:
find_injected_bins_outputs = {}

# Coreutils 
find_injected_bins_outputs['coreutils'] = !find_bins ../../dataset-gen-injected/coreutils-8.31/ | grep -v gnulib-tests | grep -v libstdbuf.so
# Util-linux
find_injected_bins_outputs['util-linux'] = !find_bins ../../dataset-gen-injected/util-linux-2.35/
# Diffutils
find_injected_bins_outputs['diffutils'] = !find_bins ../../dataset-gen-injected/diffutils-3.7/
# Inet utils
find_injected_bins_outputs['inetutils'] = !find_bins ../../dataset-gen-injected/inetutils-1.9.4/

# Flatten list
injected_bin_paths = list([str(x) for sublist in find_injected_bins_outputs.values() for x in sublist])
len(injected_bin_paths)

215

In [38]:
# Any stragglers?
injected_forcompare = [x.replace("/dataset-gen-injected/", "/dataset-gen/") for x in injected_bin_paths]
set(clean_bin_paths)-set(injected_forcompare)

set()

In [39]:
import ace
import pandas as pd
import time
import os

injected_profiles=[]
injected_runtimes={}
for bin_path in injected_bin_paths:
    if os.path.isfile(bin_path):
        src_path = get_src_dir(bin_path, "../../dataset-gen-injected")
        start = time.monotonic()
        print("Profiling {} ({} KB)".format(bin_path, os.path.getsize(bin_path)/1000))
        injected_profiles.append(ace.full_profile(bin_path, 
                                                  threads = 8, 
                                                  ins_sort = True, 
                                                  src_only = True, 
                                                  src_path = src_path
                                                 )
                                )
        injected_runtimes[bin_path] = time.monotonic() - start

Profiling ../../dataset-gen-injected/coreutils-8.31/src/[ (227.256 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/b2sum (290.152 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/base32 (183.672 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/base64 (183.056 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/basename (146.088 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/basenc (226.536 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/cat (168.576 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/chcon (298.592 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/chgrp (296.96 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/chmod (278.376 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/chown (304.952 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/chroot (181.384 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/cksum (155.472 KB)
Profiling ../../dataset-g

Profiling ../../dataset-gen-injected/coreutils-8.31/src/tr (210.6 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/true (138.152 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/truncate (166.416 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/tsort (174.28 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/tty (139.872 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/uname (143.232 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/unexpand (165.888 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/uniq (206.888 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/unlink (143.464 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/uptime (220.008 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/users (153.248 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/vdir (629.208 KB)
Profiling ../../dataset-gen-injected/coreutils-8.31/src/wc (219.096 KB)
Profiling ../../dataset-gen-inj

Profiling ../../dataset-gen-injected/inetutils-1.9.4/src/tftp (312.456 KB)
Profiling ../../dataset-gen-injected/inetutils-1.9.4/src/tftpd (282.304 KB)
Profiling ../../dataset-gen-injected/inetutils-1.9.4/src/traceroute (277.856 KB)
Profiling ../../dataset-gen-injected/inetutils-1.9.4/src/uucpd (240.448 KB)
Profiling ../../dataset-gen-injected/inetutils-1.9.4/talk/talk (317.752 KB)
Profiling ../../dataset-gen-injected/inetutils-1.9.4/talkd/talkd (343.88 KB)
Profiling ../../dataset-gen-injected/inetutils-1.9.4/telnet/telnet (543.896 KB)
Profiling ../../dataset-gen-injected/inetutils-1.9.4/telnetd/telnetd (432.088 KB)
Profiling ../../dataset-gen-injected/inetutils-1.9.4/tests/identify (20.032 KB)
Profiling ../../dataset-gen-injected/inetutils-1.9.4/tests/ls (106.224 KB)
Profiling ../../dataset-gen-injected/inetutils-1.9.4/whois/whois (311.64 KB)


In [40]:
injected_fps = pd.concat(injected_profiles, ignore_index=True)
injected_fps

binary  \
0        ../../dataset-gen-injected/coreutils-8.31/src/[   
1        ../../dataset-gen-injected/coreutils-8.31/src/[   
2        ../../dataset-gen-injected/coreutils-8.31/src/[   
3        ../../dataset-gen-injected/coreutils-8.31/src/[   
4        ../../dataset-gen-injected/coreutils-8.31/src/[   
...                                                  ...   
17000  ../../dataset-gen-injected/inetutils-1.9.4/who...   
17001  ../../dataset-gen-injected/inetutils-1.9.4/who...   
17002  ../../dataset-gen-injected/inetutils-1.9.4/who...   
17003  ../../dataset-gen-injected/inetutils-1.9.4/who...   
17004  ../../dataset-gen-injected/inetutils-1.9.4/who...   

                    function  address  length  \
0                     beyond     7296      60   
1            binary_operator     7408    1389   
2                      binop     6528     362   
3      clone_quoting_options    19088      54   
4               close_stdout    13328     164   
...                      ...      ...     ...   
17000               xnmalloc    38032      22   
17001              xnrealloc    38144      22   
17002               xrealloc    38080      54   
17003                xstrdup    38496      19   
17004                xzalloc    38384      23   

                                                src_path  src_line  \
0      /home/ubuntu/ace/dataset-gen-injected/coreutil...     124.0   
1      /home/ubuntu/ace/dataset-gen-injected/coreutil...     271.0   
2      /home/ubuntu/ace/dataset-gen-injected/coreutil...     183.0   
3      /home/ubuntu/ace/dataset-gen-injected/coreutil...     122.0   
4      /home/ubuntu/ace/dataset-gen-injected/coreutil...     117.0   
...                                                  ...       ...   
17000  /home/ubuntu/ace/dataset-gen-injected/inetutil...     104.0   
17001  /home/ubuntu/ace/dataset-gen-injected/inetutil...     117.0   
17002  /home/ubuntu/ace/dataset-gen-injected/inetutil...      51.0   
17003  /home/ubuntu/ace/dataset-gen-injected/inetutil...     119.0   
17004  /home/ubuntu/ace/dataset-gen-injected/inetutil...      84.0   

                                                src_code attributor  \
0      beyond (void)\n{\n  test_syntax_error (_("miss...       nm-t   
1      binary_operator (bool l_is_l)\n{\n  int op;\n ...       nm-t   
2      binop (char const *s)\n{\n  return ((STREQ (s,...       nm-t   
3      clone_quoting_options (struct quoting_options ...       nm-T   
4      close_stdout (void)\n{\n  if (close_stream (st...       nm-T   
...                                                  ...        ...   
17000  xnmalloc (size_t n, size_t s)\n{\n  if (xalloc...       nm-T   
17001  xnrealloc (void *p, size_t n, size_t s)\n{\n  ...       nm-T   
17002  xrealloc (void *p, size_t n)\n{\n  if (!n && p...       nm-T   
17003  xstrdup (char const *string)\n{\n  return xmem...       nm-T   
17004  xzalloc (size_t s)\n{\n  return memset (xmallo...       nm-T   

                                               raw_bytes  \
0      b'Hc\x151\xa4 \x00H\x8b\x05"\xa4 \x00SH\x8b|\x...   
1      b'AWAV\x89\xf8AUATUSH\x81\xecx\x01\x00\x00\x8b...   
2      b'I\x89\xf8H\x8d=\xfbj\x00\x00\xb9\x02\x00\x00...   
3      b'ATUSH\x89\xfb\xe8\x14\xc9\xff\xffD\x8b H\x89...   
4      b'USH\x83\xec\x08H\x8b=k\x8c \x00\xe8^-\x00\x0...   
...                                                  ...   
17000  b'H\x89\xf8H\xf7\xe6p\x05H\x89\xc7\xeb\xd3H\x8...   
17001  b'H\x89\xf0H\xf7\xe2p\x05H\x89\xc6\xeb\xb3H\x8...   
17002  b'H\x85\xf6SH\x89\xf3u\x05H\x85\xffu\x1aH\x89\...   
17003  b'SH\x89\xfb\xe87\xc6\xff\xffH\x89\xdfH\x8dp\x...   
17004  b'SH\x89\xfb\xe8w\xfe\xff\xffH\x89\xda1\xf6H\x...   

                                             fingerprint  
0      [2139169, -2147483647, 130, -131072, 2139169, ...  
1      [376, 0, 2147483647, 8388607, 0, 2147483647, -...  
2      [1, -2147483647, 128, 0, -1, -1, 19252, -1, 0,...  
3      [0, -2147483647, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,...  
4      [8, -2147483647, -21453

In [41]:
# There should be 215 additional functions in injected_fps
len(injected_fps)+len(clean_fps)-215

33580

## Analysis
Now that we have both sets of fingerprints, lets do the actual experiment

**Methodology**
1. Duplicate dataset into `clean` and `injected`.
2. Inject custom function (with known fingerprint) `peaclab_math()` into source of 20% of `injected` binaries.
3. Compile all applications with debugging information, otherwise vendor default settings.
4. Fingerprint all functions in all binaries.
5. For each fold, combine 100% (of binaries) of `clean` with 20% of `injected` (of binaries). Classify each function as `peaclab_math` or `not_peaclab_math` based on exact match to known fingerprint.
6. Count Type 1 & 2 errors and calculate F1 score.
7. Repeat 5 times, switching which 20% are injected

First, we'll set up the folds

In [42]:
# Get list of binaries and shuffle
import random
injected_binaries = list(set(injected_fps['binary']))
assert(len(injected_binaries) == 215)
random.shuffle(injected_binaries)
injected_binaries

['../../dataset-gen-injected/util-linux-2.35/mkfs',
 '../../dataset-gen-injected/util-linux-2.35/unshare',
 '../../dataset-gen-injected/coreutils-8.31/src/kill',
 '../../dataset-gen-injected/coreutils-8.31/src/truncate',
 '../../dataset-gen-injected/util-linux-2.35/logger',
 '../../dataset-gen-injected/util-linux-2.35/scriptreplay',
 '../../dataset-gen-injected/coreutils-8.31/src/factor',
 '../../dataset-gen-injected/diffutils-3.7/src/sdiff',
 '../../dataset-gen-injected/util-linux-2.35/agetty',
 '../../dataset-gen-injected/util-linux-2.35/flock',
 '../../dataset-gen-injected/inetutils-1.9.4/ping/ping',
 '../../dataset-gen-injected/coreutils-8.31/src/cut',
 '../../dataset-gen-injected/util-linux-2.35/scriptlive',
 '../../dataset-gen-injected/coreutils-8.31/src/seq',
 '../../dataset-gen-injected/diffutils-3.7/src/diff',
 '../../dataset-gen-injected/inetutils-1.9.4/src/traceroute',
 '../../dataset-gen-injected/coreutils-8.31/src/users',
 '../../dataset-gen-injected/util-linux-2.35/hardli

In [43]:
NUM_FOLDS=5
fold_size = len(injected_binaries)//NUM_FOLDS
injected_binaries_folds = [None,] * NUM_FOLDS
for i in range(NUM_FOLDS):
    injected_binaries_folds[i] = injected_binaries[i*fold_size : (i+1)*fold_size]
    print("Fold {} (size {}):".format(i, len(injected_binaries_folds[i])))
    print(injected_binaries_folds[i])

Fold 0 (size 43):
['../../dataset-gen-injected/util-linux-2.35/mkfs', '../../dataset-gen-injected/util-linux-2.35/unshare', '../../dataset-gen-injected/coreutils-8.31/src/kill', '../../dataset-gen-injected/coreutils-8.31/src/truncate', '../../dataset-gen-injected/util-linux-2.35/logger', '../../dataset-gen-injected/util-linux-2.35/scriptreplay', '../../dataset-gen-injected/coreutils-8.31/src/factor', '../../dataset-gen-injected/diffutils-3.7/src/sdiff', '../../dataset-gen-injected/util-linux-2.35/agetty', '../../dataset-gen-injected/util-linux-2.35/flock', '../../dataset-gen-injected/inetutils-1.9.4/ping/ping', '../../dataset-gen-injected/coreutils-8.31/src/cut', '../../dataset-gen-injected/util-linux-2.35/scriptlive', '../../dataset-gen-injected/coreutils-8.31/src/seq', '../../dataset-gen-injected/diffutils-3.7/src/diff', '../../dataset-gen-injected/inetutils-1.9.4/src/traceroute', '../../dataset-gen-injected/coreutils-8.31/src/users', '../../dataset-gen-injected/util-linux-2.35/hardl

Now, lets get the fingerprint for peaclab_math()

In [44]:
injected_fps["fingerprint_tuple"] = injected_fps.fingerprint.apply(lambda x: tuple(x))
peaclab_math_fps = injected_fps[injected_fps.function == "peaclab_math"].fingerprint_tuple.unique()
peaclab_math_fps

array([(120, -2147483647, -2147483648, -134217728, 0, -2147483648, 0, 40, 104, 0, 40, 2, 9626, 38505, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
       (0, -2147483647, 0, 0, 38505, 0, 0, 0, 0, 0, 0, 0, 38505, 0, 0, 0, 0, 0, 0, 0, 38505, 1685646467, 1685646467, 0, 0, 0, 0, 0, 0, 0, 0, 0)],
      dtype=object)

In [45]:
fp0_len = len(injected_fps[injected_fps.fingerprint_tuple == peaclab_math_fps[0]])
fp1_len = len(injected_fps[injected_fps.fingerprint_tuple == peaclab_math_fps[1]])
print("{} binaries have peaclab_math_fp[0]".format(fp0_len))
print("{} binaries have peaclab_math_fp[1]".format(fp1_len))
list(injected_fps[injected_fps.fingerprint_tuple == peaclab_math_fps[1]].binary)

213 binaries have peaclab_math_fp[0]
2 binaries have peaclab_math_fp[1]


['../../dataset-gen-injected/util-linux-2.35/ipcmk',
 '../../dataset-gen-injected/util-linux-2.35/mcookie']

So there's 2 different fingerprints for peaclab_do_math... Which means that, since we're assuming exact match, we're gonna get those 2 binaries wrong. This should be okay, 2 out of 215 is still 99.07% accuracy (assuming we have no false positives). To be extra fair though, we should profile a binary that *only* contains peaclab_do_math. Hopefully it matches `peaclab_math_fps[0]`

In [46]:
sample_profile = ace.full_profile("../../dataset-gen-injected/peaclab_math/peaclab_math",threads = 1,ins_sort = True,src_only = True,src_path = "../../dataset-gen-injected/peaclab_math/")
display(sample_profile[sample_profile.function == "peaclab_math"])
test_fp = tuple(list(sample_profile[sample_profile.function == "peaclab_math"].fingerprint)[0])
display(test_fp == peaclab_math_fps[0])
display(test_fp == peaclab_math_fps[1])

binary      function  address  \
4  ../../dataset-gen-injected/peaclab_math/peacla...  peaclab_math     1786   

   length                                           src_path  src_line  \
4     230  /home/ubuntu/ace/dataset-gen-injected/peaclab_...       3.0   

                                            src_code attributor  \
4  int peaclab_math() {\n    volatile int num;\n ...       nm-T   

                                           raw_bytes  \
4  b'UH\x89\xe5H\x83\xecpdH\x8b\x04%(\x00\x00\x00...   

                                         fingerprint  
4  [112, -2147483647, -2147483609, -134217726, 0,...

False

False

It matches neither... Cool. Alright, let's just check for false positives and wrap it up

In [47]:
clean_fps["fingerprint_tuple"] = clean_fps.fingerprint.apply(lambda x: tuple(x))
fp0_len = len(clean_fps[clean_fps.fingerprint_tuple == peaclab_math_fps[0]])
fp1_len = len(clean_fps[clean_fps.fingerprint_tuple == peaclab_math_fps[1]])
print("{} clean binaries have peaclab_math_fp[0]".format(fp0_len))
print("{} clean binaries have peaclab_math_fp[1]".format(fp1_len))

0 clean binaries have peaclab_math_fp[0]
0 clean binaries have peaclab_math_fp[1]


*sigh of relief*

And now let's just make sure that there's no false positives in the injected_fps set.

In [48]:
display(injected_fps[injected_fps.fingerprint_tuple == peaclab_math_fps[0]].function.unique())
display(injected_fps[injected_fps.fingerprint_tuple == peaclab_math_fps[1]].function.unique())

array(['peaclab_math'], dtype=object)

array(['peaclab_math'], dtype=object)

Looks good. So overall that's 2 false negatives 0 false positives, 213 true positives, and 33580 true negatives. That amounts to stats of:

In [49]:
FN = 2
FP = 0
TP = 213
TN = 33580
precision = TP/(TP+FP)
recall = TP/(TP+FN)
f1 = (2*(recall * precision)) / (recall + precision)
display("Precision={} Recall={} F1={}".format(precision, recall, f1))

'Precision=1.0 Recall=0.9906976744186047 F1=0.9953271028037384'

In [50]:
33580+215

33795

Let's also check how many different binary patterns there are.

In [51]:
peaclab_math_raw_bytes = injected_fps[injected_fps.function == "peaclab_math"].raw_bytes.unique()

In [53]:
len(peaclab_math_raw_bytes)

205